# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            tsi
tagline:          'developer. designer. tech enthusiast.'
description:	  'thesaadismail'
url:              http://thesaadismail.github.io
paginate:         1
baseurl:          /
author:
  name:           Saad Ismail
  url:            https://twitter.com/thesaadismail
  email:          noemail@noemail.com

# Custom vars
archiveurl:	  /archive/
version:          1.0.0
github:
  repo:           https://github.com/thesaadismail/thesaadismail.github.io
